import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { FileUpload } from "@/components/file-upload";
import { 
  CheckCircle, 
  XCircle, 
  AlertTriangle, 
  FileText, 
  Upload, 
  ArrowRight,
  RefreshCw
} from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { type UploadedFile } from "@shared/schema";

interface XSLTValidationProps {
  projectId: string;
  onProceedToMapping: () => void;
  xsltValidation?: {
    isValid: boolean;
    errors: string[];
    warnings: string[];
    confidenceScore: number;
    matchesExpected?: boolean;
  };
}

export function XSLTValidationStep({
  projectId,
  onProceedToMapping,
  xsltValidation
}: XSLTValidationProps) {
  const [isValidating, setIsValidating] = useState(false);
  const queryClient = useQueryClient();

  // Get project files
  const { data: files = [], refetch: refetchFiles } = useQuery({
    queryKey: ["/api/projects", projectId, "files"],
    enabled: !!projectId,
  });

  const xsltSourceFile = (files as UploadedFile[]).find((f: UploadedFile) => f.systemType === "xslt_source");
  const xsltGeneratedFile = (files as UploadedFile[]).find((f: UploadedFile) => f.systemType === "xslt_generated");
  const xsltFile = (files as UploadedFile[]).find((f: UploadedFile) => f.systemType === "xslt_file");

  // Validate XSLT mutation
  const validateXSLTMutation = useMutation({
    mutationFn: async () => {
      setIsValidating(true);
      const response = await apiRequest("POST", `/api/projects/${projectId}/validate-xslt`);
      return response.json();
    },
    onSuccess: (validationResult) => {
      setIsValidating(false);
      // Invalidate project query to refresh the validation results
      queryClient.invalidateQueries({ queryKey: ["/api/projects", projectId] });
      
      if (validationResult.isValid) {
        // Auto-proceed to mapping step if validation is successful
        setTimeout(() => {
          onProceedToMapping();
        }, 2000);
      }
    },
    onError: () => {
      setIsValidating(false);
    }
  });

  const handleFileUploaded = async (file: UploadedFile) => {
    await refetchFiles();
  };

  const handleFileDeleted = () => {
    refetchFiles();
  };

  const canValidate = xsltSourceFile && xsltGeneratedFile && xsltFile;
  const hasValidationResults = !!xsltValidation;
  
  // Use the latest validation result from either the prop or the mutation result
  const latestValidationResult = validateXSLTMutation.data || xsltValidation;

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <FileText className="h-5 w-5" />
            <span>XSLT Validation</span>
          </CardTitle>
          <p className="text-muted-foreground">
            Upload your source XML file, generated JSON file, and XSLT transformation file to validate that the XSLT correctly transforms the XML to match the expected JSON output.
          </p>
        </CardHeader>
      </Card>

      {/* File Upload Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <FileUpload
          projectId={projectId}
          systemType="xslt_source"
          onFileUploaded={handleFileUploaded}
          onFileDeleted={handleFileDeleted}
          uploadedFile={xsltSourceFile}
          title="Source XML File"
          description="Upload the original XML file that needs to be transformed"
          acceptedFileTypes=".xml"
          data-testid="upload-xslt-source"
        />
        
        <FileUpload
          projectId={projectId}
          systemType="xslt_generated"
          onFileUploaded={handleFileUploaded}
          onFileDeleted={handleFileDeleted}
          uploadedFile={xsltGeneratedFile}
          title="Generated JSON File"
          description="Upload the JSON file generated by IntegrationHub that represents the expected output"
          acceptedFileTypes=".json"
          data-testid="upload-xslt-generated"
        />
        
        <FileUpload
          projectId={projectId}
          systemType="xslt_file"
          onFileUploaded={handleFileUploaded}
          onFileDeleted={handleFileDeleted}
          uploadedFile={xsltFile}
          title="XSLT Transformation File"
          description="Upload your XSLT file that should transform the XML to match the JSON"
          acceptedFileTypes=".xsl,.xslt"
          data-testid="upload-xslt-file"
        />
      </div>

      {/* Validation Action */}
      {canValidate && (
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold mb-2">Ready to Validate</h3>
                <p className="text-muted-foreground">
                  All required files have been uploaded. Click validate to test your XSLT transformation.
                </p>
              </div>
              <Button
                onClick={() => validateXSLTMutation.mutate()}
                disabled={isValidating}
                size="lg"
                data-testid="button-validate-xslt"
              >
                {isValidating ? (
                  <>
                    <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                    Validating...
                  </>
                ) : (
                  <>
                    <CheckCircle className="mr-2 h-4 w-4" />
                    Validate XSLT
                  </>
                )}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Validation Results */}
      {(hasValidationResults || latestValidationResult) && (
        <Card data-testid="xslt-validation-result">
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              {latestValidationResult.isValid ? (
                <CheckCircle className="h-5 w-5 text-green-600" />
              ) : (
                <XCircle className="h-5 w-5 text-red-600" />
              )}
              <span>Validation Results</span>
              <Badge variant={latestValidationResult.isValid ? "default" : "destructive"}>
                {latestValidationResult.isValid ? "Passed" : "Failed"}
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Confidence Score */}
            <div className="flex items-center justify-between p-4 bg-muted rounded-lg" data-testid="xslt-confidence">
              <span className="font-medium">Confidence Score</span>
              <div className="flex items-center space-x-2">
                <div className="w-20 bg-gray-200 rounded-full h-2">
                  <div 
                    className={`h-2 rounded-full ${
                      latestValidationResult.confidenceScore >= 80 ? 'bg-green-600' :
                      latestValidationResult.confidenceScore >= 60 ? 'bg-yellow-600' :
                      'bg-red-600'
                    }`}
                    style={{ width: `${latestValidationResult.confidenceScore}%` }}
                  />
                </div>
                <span className="font-semibold">{latestValidationResult.confidenceScore}%</span>
              </div>
            </div>

            {/* Expected Match Status */}
            {latestValidationResult.matchesExpected !== undefined && (
              <div className="flex items-center space-x-2 p-4 bg-muted rounded-lg">
                {latestValidationResult.matchesExpected ? (
                  <CheckCircle className="h-4 w-4 text-green-600" />
                ) : (
                  <XCircle className="h-4 w-4 text-red-600" />
                )}
                <span className="font-medium">
                  Transformation {latestValidationResult.matchesExpected ? "matches" : "does not match"} expected output
                </span>
              </div>
            )}

            {/* Errors */}
            {latestValidationResult.errors && latestValidationResult.errors.length > 0 && (
              <Alert variant="destructive" data-testid="xslt-validation-errors">
                <XCircle className="h-4 w-4" />
                <AlertTitle>Validation Errors</AlertTitle>
                <AlertDescription>
                  <ul className="list-disc list-inside space-y-1 mt-2">
                    {latestValidationResult.errors.map((error: string, index: number) => (
                      <li key={index} className="text-sm">{error}</li>
                    ))}
                  </ul>
                </AlertDescription>
              </Alert>
            )}

            {/* Warnings */}
            {latestValidationResult.warnings && latestValidationResult.warnings.length > 0 && (
              <Alert data-testid="xslt-validation-warnings">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>Warnings</AlertTitle>
                <AlertDescription>
                  <ul className="list-disc list-inside space-y-1 mt-2">
                    {latestValidationResult.warnings.map((warning: string, index: number) => (
                      <li key={index} className="text-sm">{warning}</li>
                    ))}
                  </ul>
                </AlertDescription>
              </Alert>
            )}

            {/* Actions */}
            <div className="flex justify-between pt-4">
              <Button variant="outline" onClick={() => validateXSLTMutation.mutate()}>
                <RefreshCw className="mr-2 h-4 w-4" />
                Re-validate
              </Button>
              
              {latestValidationResult.isValid && (
                <Button onClick={onProceedToMapping} data-testid="button-proceed-mapping">
                  Proceed to Field Mapping
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Help Text */}
      {!canValidate && (
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <Upload className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">Upload Required Files</h3>
              <p className="text-muted-foreground">
                Upload all three files above to begin XSLT validation. This step ensures your transformation logic correctly converts XML to the expected JSON format.
              </p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}